[package]
name = "butler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = { version = "0.10.0", features = ["macros", "auto-send"] }
tokio = { version = "1.20.0", features = ["full"] }
dotenv = "0.15.0"
anyhow = "1.0.58"
reqwest = "0.11.11"
serde = { version = "1.0.138", features = ["derive"]}
serde_json = "1.0.82"
chrono = "0.4.19"
redis = { version = "0.21.5", features = ["tokio-comp", "connection-manager"] }
async-trait = "0.1.56"
rand = "0.8.5"
